### ISSUE TITLE
Implement commit_contains(commit_hash, commit_blob)bool UDF

### ISSUE THREAD

**Issue by jfontan** [src-d/gitquery#132]
Depends on https://github.com/src-d/go-mysql-server/issues/1

Previous comments:

* @erizocosmico 

> This is missing the repo_id parameter, right?

* @ajnavarro:

> After a talk we decided to do not add repo_id. The performance of that udfs will be improved using indexes. At the begining will be really slow.

* @erizocosmico:

> So, if the `repo_id` is missing and the only things the UDF has are `commit_hash` and `commit_blob`, how are we supposed to retrieve that info?

> Repository Pool does not have all repositories opened, right? So you can't just iterate them all until you find a match. The UDF should receive something with the repo associated to the given row or something along those lines. Otherwise, where is the UDF supposed to look for?

* @ajnavarro:

> Given a commit hash, it will always contains the specified blob or not. In the future, we will have a bitmap index to be able to answer this kind of questions. Right now, the only way that we have to do it is iterate over all the repositories.

> Also, if the commit is repeated in several repositories, it will appears n times on the result.

> Also, you don't need to have all the repositories opened, you can iterate them and send commits per each repository, and filter that ones that does not match.

* @erizocosmico:

> So, for each row that uses that UDF we have to iterate all repositories again?

* @ajnavarro:

> Right now, yes. In the future it will be a simple query to an index. Also the UDF can be improved to be executed at the table iterator level, like another column. Doing this, you don't need to iterate over all the repositories per each column again.

**Comment by erizocosmico** [comment]
This requires a session with the repository pool or something similar to be available before it's implemented.

**Comment by ajnavarro** [comment]
Related discussion: https://github.com/src-d/go-mysql-server/issues/36
