### ISSUE TITLE
commit_has_tree(commit_hash, tree_hash) UDF

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitquery#152]
We have ways of joining almost all tables in gitquery, except commits and trees.

- repositories and remotes join by repo id.
- repositories and refs join by repo id.
- refs and commits join using history_idx udf.
- commits and blobs join using commit_contains udf.
- trees and blobs join using blob.hash and tree_entries.entry_hash.
- trees and commits don't have anything to join.

We could have another UDF to perform the join between these two tables:

```
commit_has_tree(commit_hash, tree_hash)
```

For example, select commit messages with Go files:

```sql
SELECT message 
FROM commits 
  INNER JOIN tree_entries 
  ON commit_has_tree(hash, tree_hash) 
WHERE name LIKE '%.go';
```

If we add this UDF, I also propose to rename `commit_contains` to `commit_has_blob`, because commit can contain many things and is consistent with this naming.

Thoughts? /cc @mcarmonaa @jfontan @ajnavarro

**Comment by erizocosmico** [comment]
@ajnavarro Should we rename `commit_contains` to `commit_has_blob`, then?

**Comment by ajnavarro** [comment]
@erizocosmico makes sense
