### ISSUE TITLE
Add integration test to get the number of repositories created per year

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitquery#160]

**Comment by erizocosmico** [comment]
Do you mean the number of repositories per year of the first commit, right? If it's that, this is currently blocked by not having the parents in the commit row.

Query would be something like:

```sql
SELECT COUNT(*), YEAR(commit_date) 
FROM (
  SELECT * 
  FROM commits 
  WHERE parent_commits(hash) = 0 
  ORDER BY commit_date 
  LIMIT 1
) commits
GROUP BY commit_date
```

As you can see, we need a way of telling if a commit has no parents.

We _could_ do with just returning the first commit according to the date, but might not be accurate:

```sql
SELECT COUNT(*), YEAR(commit_date) 
FROM (
  SELECT * 
  FROM commits 
  ORDER BY commit_date 
  LIMIT 1
) commits
GROUP BY commit_date
```

Would that be enough?
