### ISSUE TITLE
Create first version of gitBase

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitquery#162]
After finish implementing all the needed features for an MVP version creates a first release of the DB.

**Comment by erizocosmico** [comment]
Should we add a task for renaming gitquery to gitbase? Or is the name still WIP?

**Comment by ajnavarro** [comment]
As far as I know, is a WIP

**Comment by jfontan** [comment]
We should update dependencies before creating the first version. I believe there are new ones.

**Comment by ajnavarro** [comment]
PR: https://github.com/src-d/gitquery/pull/187
