### ISSUE TITLE
Queries can not be cancelled

### ISSUE THREAD

**Issue by jfontan** [src-d/gitquery#174]
After cancelling a query it continues running in the server.

**Comment by jfontan** [comment]
When a query is cancelled its callback is not immediately called. The same happens when the connection is lost and `Handler.ConnectionClosed` is not called until some timeout passes.

To cancel a query the client sends a `KILL` command:

```sql
KILL QUERY 1
```
Queries should be registered by query ID and cancelled when this message is received. This has to be done in `go-mysql-server`.

**Comment by erizocosmico** [comment]
Yup, this should be done in the `SessionManager` inside `go-mysql-server`.

I'm assuming the IDs are just an auto-incrementable number with the number of queries executed so far, right?

**Comment by jfontan** [comment]
ID is ConnectionID. I have already working code to save connection structures to close the connection when needed (`KILL CONNECTION`).

**Comment by erizocosmico** [comment]
I mean in `KILL QUERY FOO`

**Comment by jfontan** [comment]
There are two flavours of `KILL`. Both kill the query but one of them (`KILL CONNECTION`) also kills the connection.

https://dev.mysql.com/doc/refman/5.7/en/kill.html
