### ISSUE TITLE
Optimize commit_has_blob and commit_has_tree

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitquery#191]
Find a way to optimize this Function, using cache or another kind of index.

**Comment by ajnavarro** [comment]
To improve the performance of this, we can add two LRU caches to store the most used blobs and trees info on memory. We can use this implementation from hashicorp: https://github.com/hashicorp/golang-lru

When a repo is already iterated, the cache should be purged.

**Comment by erizocosmico** [comment]
All repos are iterated every time the function is executed (because we don't know where the targets are) and there is no repeated access to any commit, tree or blob during an execution, so an LRU cache that gets purged every time the repo is iterated is useless.
